export enum QUERY_KEYS {
  ARTIST = 'ARTIST',
  CHARTS = 'CHARTS',
  DETAIL_PLAYLIST = 'DETAIL_PLAYLIST',
  HOME_PLAYLIST = 'HOME_PLAYLIST',
  HOME_BANNER = 'HOME_BANNER',
  MV_LIST = 'MV_LIST',
  MV_DETAIL = 'MV_DETAIL',
  SEARCH = 'SEARCH',
  SONG = 'SONG',
  SONG_INFO = 'SONG_INFO',
  TOP_100 = 'TOP_100',
}
